# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#pod 'SideMenu'

pod 'MBProgressHUD'
# add the Firebase pod for Google Analytics
# add pods for any other desired Firebase products


# https://firebase.google.com/docs/ios/setup#available-pods

target 'SampleGigatmsSDK' do
  
end
target 'LoginReaderDemo' do

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Realm'
end


target 'UHFSample' do
  
end

